/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PersonalData, Experience, AcademicCourse, Certificate, SkillItem } from './types';

export const personalData: PersonalData = {
  name: 'Nícolas Sinclair Oliveira Barbosa',
  age: 28,
  birthDate: '1998-03-23',
  cpf: '042.624.915-10',
  email: 'nsobarbosa@gmail.com',
  secondaryEmail: 'nicolassinclair777@gmail.com',
  phone: '71 9 9391-8247',
  celular: '71 9 8173-1545',
  salaryExpectation: 'R$ 2.000,00',
  location: 'Salvador, Bahia',
  country: 'Brasil',
  photoUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQEJLouEbhbG_A/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1712768805161?e=1781740800&v=beta&t=F4_0m13av75QPciRuc5WO5IhyikdmrXdMNn9SmIZOlc',
  languages: [
    { language: 'Português', level: 'Domínio' },
    { language: 'Inglês', level: 'Intermediário' },
    { language: 'Espanhol', level: 'Básico' },
  ],
  diversity: {
    gender: 'Masculino',
    cisTrans: 'Cisgênero',
    sex: 'Homem',
    raceColor: 'Parda',
    orientation: 'Heterossexual',
  },
};

export const experiences: Experience[] = [
  {
    id: 'exp1',
    role: 'Assistente Administrativo Financeiro',
    company: 'MS Condomínios (Administração Condominial)',
    description: 'Atuação na área financeira com foco em contas a pagar, atendendo múltiplos CNPJs simultaneamente, garantindo organização, controle e cumprimento de prazos.',
    periodStart: '06/2025',
    periodEnd: '10/2025',
    durationMonths: 4,
    keyActivities: [
      'Controle e lançamento de contas a pagar, gestão de fluxo financeiro e acompanhamento de vencimentos.',
      'Conciliação bancária em diferentes instituições financeiras, assegurando a precisão das informações.',
      'Gestão financeira de múltiplos condomínios, atendendo um alto volume de demandas de forma simultânea.',
      'Elaboração de relatórios financeiros mensais para suporte direto à tomada de decisão estratégica da diretoria.',
      'Realização e cotação de compras de insumos corporativos e contratação de prestadores de serviços, com negociação comercial ativa.',
      'Apoio técnico na elaboração de atas, acompanhamento de assembleias e aplicação de multas/advertências segundo regimento condominial.',
      'Atendimento direto e personalizado a síndicos, condôminos e fornecedores, garantindo transparência e agilidade.',
    ],
  },
  {
    id: 'exp2',
    role: 'Analista Administrativo Financeiro – Consórcios',
    company: 'BM Corporation',
    description: 'Atuação generalista nas áreas administrativa e financeira com responsabilidade integral pelos processos internos da operação de consórcios, desde a formalização técnica até o monitoramento detalhado do pós-venda.',
    periodStart: '07/2023',
    periodEnd: '02/2025',
    durationMonths: 19,
    keyActivities: [
      'Elaboração, conferência detalhada e gestão ativa de contratos corporativos de clientes e de administradoras de consórcio.',
      'Controle rigoroso de fluxos de pagamento, emissão de repasses financeiros e acompanhamento detalhado de contas ativas.',
      'Gestão pontual do processo de contemplações de cotas, assegurando conformidade burocrática e liberação de créditos.',
      'Análise crítica de garantias, conferência de documentação pessoal e societária conforme diretrizes de compliance.',
      'Desenvolvimento de relatórios gerenciais e dashboards financeiros para apoiar a diretoria administrativa em decisões de investimentos.',
      'Relacionamento estratégico diário com instituições bancárias, administradoras parceiras e clientes de alto valor.',
    ],
  },
  {
    id: 'exp3',
    role: 'Assistente Administrativo – Área de Serviços (Varejo)',
    company: 'Grupo Ramiro Campelo (Lojas Guaibim, Casas + Fácil e Motorola)',
    description: 'Atuação operacional e analítica no suporte administrativo à área de vendas de serviços das bandeiras do grupo, mapeando o desempenho comercial e gerando inteligência competitiva.',
    periodStart: '08/2022',
    periodEnd: '07/2023',
    durationMonths: 11,
    keyActivities: [
      'Elaboração semanal e análise minuciosa de relatórios gerenciais e indicadores chaves de desempenho (KPIs) das lojas físicas.',
      'Monitoramento de metas e vendas de seguros e serviços vinculados, fornecendo direcionamentos analíticos por unidade.',
      'Suporte consultivo completo para gerentes regionais e times de venda na tomada de decisões em relação a metas de serviços.',
      'Consolidação, estruturação e auditoria de dados comerciais provenientes de múltiplos sistemas das filiais.',
      'Identificação proativa de oportunidades de melhoria de margem de contribuição com base em análises estatísticas históricas.',
    ],
  },
  {
    id: 'exp4',
    role: 'Analista de Defesas e Odds / Suporte Técnico',
    company: 'Arena Esportiva (Plataforma de Apostas Esportivas)',
    description: 'Início em suporte técnico com rápido crescimento para análise avançada de odds, modelagem estatística operacional de bilhetes e auditoria de pontos comerciais em rede nacional.',
    periodStart: '02/2021',
    periodEnd: '11/2022',
    durationMonths: 21,
    keyActivities: [
      'Prestação de suporte técnico de nível 2 para pontos de vendas parceiros em todo o Brasil, lidando com impressoras térmicas e tablets.',
      'Configuração, monitoramento, precificação dinâmica e ajuste estatístico de odds de apostas esportivas na plataforma.',
      'Auditoria de riscos em bilhetes e verificação de fraudes operacionais e conformidade com as regras gerais rígidas da marca.',
      'Análise comparativa constante de mercado (benchmarking) em relação a odds de concorrentes diretos.',
      'Identificação de bugs de sistema e envio de chamados detalhados de engenharia de software para otimização da plataforma.',
    ],
  },
  {
    id: 'exp5',
    role: 'Jovem Aprendiz Administrativo – Área Financeira',
    company: 'Santa Casa de Misericórdia da Bahia (Faturamento Hospitalar)',
    description: 'Iniciação profissional com foco em rotinas de suporte do departamento financeiro e rápida evolução para atuar na auditoria técnica de faturamento de contas médicas e relacionamento com operadoras de saúde.',
    periodStart: '01/2018',
    periodEnd: '05/2019',
    durationMonths: 16,
    keyActivities: [
      'Coleta de prontuários, preenchimento de guias de autorização médicas e organização rigorosa de documentos de faturamento público e privado.',
      'Auditoria preliminar de itens lançados em contas de internação hospitalar frente aos relatórios de enfermagem.',
      'Envio eletrônico de faturas de contas de convênios médicos via padrão XML TISS/TUSS.',
      'Apoio em conciliações de glosas médicas e acompanhamento administrativo de processos de cobrança em aberto.',
    ],
  },
];

export const academicCourses: AcademicCourse[] = [
  {
    id: 'gfin',
    name: 'Tecnólogo em Gestão Financeira',
    curriculum: '2023/1',
    classGroup: 'GFIN02',
    situation: 'Ativo',
    expectedConclusion: 2027,
    completedHours: 140, // 2 subjects completed * 70 = 140
    extraHoursRequired: 100,
    extraHoursCompleted: 0,
    etapas: [
      {
        etapa: 1,
        subjects: [
          { code: '3411', name: 'INTRODUÇÃO AO CURSO DE GESTÃO FINANCEIRA', ch: 70, media: 8.0, frequency: 100, status: 'Aprovado' },
          { code: '928', name: 'FUNDAMENTOS DA ADMINISTRAÇÃO', ch: 70, media: 8.7, frequency: 100, status: 'Aprovado' },
        ],
      },
      {
        etapa: 2,
        subjects: [
          { code: '2585', name: 'ANÁLISE DE INVESTIMENTOS', ch: 70, status: 'em Curso' },
          { code: '27', name: 'ECONOMIA', ch: 70, status: 'em Curso' },
          { code: '3323', name: 'ACE - SUSTENTABILIDADE', ch: 100, status: 'em Curso' },
          { code: '521', name: 'CONTABILIDADE GERAL', ch: 70, status: 'em Curso' },
        ],
      },
      {
        etapa: 3,
        subjects: [
          { code: '2308', name: 'NEGÓCIOS ELETRÔNICOS', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '298', name: 'PSICOLOGIA ORGANIZACIONAL', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '66', name: 'MARKETING DIGITAL', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
        ],
      },
      {
        etapa: 4,
        subjects: [
          { code: '1191', name: 'FUNDAMENTOS DO MARKETING', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '148', name: 'EMPREENDEDORISMO', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '2511', name: 'DIREITO EMPRESARIAL', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '428', name: 'PROJETO INTEGRADOR I', ch: 100, status: 'a Cursar', reprovadoAnteriormente: true },
        ],
      },
      {
        etapa: 5,
        subjects: [
          { code: '2426', name: 'GESTÃO ORÇAMENTÁRIA', ch: 70, status: 'a Cursar' },
          { code: '2586', name: 'ANÁLISE DAS DEMONSTRAÇÕES CONTÁBEIS', ch: 70, status: 'a Cursar' },
          { code: '31', name: 'MATEMÁTICA FINANCEIRA', ch: 70, status: 'a Cursar' },
        ],
      },
      {
        etapa: 6,
        subjects: [
          { code: '177', name: 'GESTÃO DE PROJETOS', ch: 70, status: 'a Cursar' },
          { code: '1886', name: 'PROJETO INTEGRADOR II', ch: 100, status: 'a Cursar' },
          { code: '227', name: 'GESTÃO DE CUSTOS', ch: 70, status: 'a Cursar' },
          { code: '2561', name: 'FINANÇAS CORPORATIVAS', ch: 70, status: 'a Cursar' },
          { code: 'A164', name: 'AVALIAÇÃO INTEGRADA I - GESTÃO FINANCEIRA', ch: 70, status: 'a Cursar' },
          { code: 'F00482', name: 'ACE - INCLUSÃO', ch: 100, status: 'a Cursar' },
        ],
      },
    ],
  },
  {
    id: 'adm',
    name: 'Bacharelado em Administração',
    curriculum: '2023/1',
    classGroup: 'ADM02',
    situation: 'Ativo',
    expectedConclusion: 2028,
    completedHours: 140, // 2 subjects completed * 70 = 140
    extraHoursRequired: 100,
    extraHoursCompleted: 0,
    etapas: [
      {
        etapa: 1,
        subjects: [
          { code: '3389', name: 'INTRODUÇÃO AO CURSO DE ADMINISTRAÇÃO', ch: 70, media: 9.0, frequency: 100, status: 'Aprovado' },
          { code: '928', name: 'FUNDAMENTOS DA ADMINISTRAÇÃO', ch: 70, media: 8.7, frequency: 100, status: 'Aprovado' },
        ],
      },
      {
        etapa: 2,
        subjects: [
          { code: '117', name: 'COMUNICAÇÃO E EXPRESSÃO', ch: 70, status: 'em Curso' },
          { code: '177', name: 'GESTÃO DE PROJETOS', ch: 70, status: 'em Curso' },
          { code: '27', name: 'ECONOMIA', ch: 70, status: 'em Curso' },
          { code: '3323', name: 'ACE - SUSTENTABILIDADE', ch: 100, status: 'em Curso' },
        ],
      },
      {
        etapa: 3,
        subjects: [
          { code: '2308', name: 'NEGÓCIOS ELETRÔNICOS', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '66', name: 'MARKETING DIGITAL', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
        ],
      },
      {
        etapa: 4,
        subjects: [
          { code: '148', name: 'EMPREENDEDORISMO', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '1566', name: 'SOCIOLOGIA GERAL', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '428', name: 'PROJETO INTEGRADOR I', ch: 50, status: 'a Cursar', reprovadoAnteriormente: true },
          { code: '521', name: 'CONTABILIDADE GERAL', ch: 70, status: 'a Cursar', reprovadoAnteriormente: true },
        ],
      },
      {
        etapa: 5,
        subjects: [
          { code: '173', name: 'PLANEJAMENTO ESTRATÉGICO', ch: 70, status: 'a Cursar' },
          { code: '2422', name: 'GESTÃO DE PESSOAS', ch: 70, status: 'a Cursar' },
          { code: '2426', name: 'GESTÃO ORÇAMENTÁRIA', ch: 70, status: 'a Cursar' },
        ],
      },
      {
        etapa: 6,
        subjects: [
          { code: '1742', name: 'ADMINISTRAÇÃO DE MATERIAIS E PATRIMÔNIO', ch: 70, status: 'a Cursar' },
          { code: '227', name: 'GESTÃO DE CUSTOS', ch: 70, status: 'a Cursar' },
          { code: '2511', name: 'DIREITO EMPRESARIAL', ch: 70, status: 'a Cursar' },
          { code: 'A11', name: 'AVALIAÇÃO INTEGRADA I - ADMINISTRAÇÃO', ch: 35, status: 'a Cursar' },
          { code: 'F00482', name: 'ACE - INCLUSÃO', ch: 100, status: 'a Cursar' },
        ],
      },
      {
        etapa: 7,
        subjects: [
          { code: '2509', name: 'MANUFATURA ENXUTA', ch: 70, status: 'a Cursar' },
          { code: '2585', name: 'ANÁLISE DE INVESTIMENTOS', ch: 70, status: 'a Cursar' },
          { code: '298', name: 'PSICOLOGIA ORGANIZACIONAL', ch: 70, status: 'a Cursar' },
        ],
      },
      {
        etapa: 8,
        subjects: [
          { code: '1403', name: 'FUNDAMENTOS DA GESTÃO PÚBLICA', ch: 70, status: 'a Cursar' },
          { code: '1586', name: 'MAPEAMENTO E GERENCIAMENTO DE PROCESSOS', ch: 70, status: 'a Cursar' },
          { code: '1652', name: 'SISTEMAS DE CANAIS DE DISTRIBUIÇÃO', ch: 70, status: 'a Cursar' },
          { code: '1886', name: 'PROJETO INTEGRADOR II', ch: 50, status: 'a Cursar' },
          { code: 'A12', name: 'AVALIAÇÃO INTEGRADA II - ADMINISTRAÇÃO', ch: 35, status: 'a Cursar' },
        ],
      },
      {
        etapa: 9,
        subjects: [
          { code: '1323', name: 'DIREITO INDIVIDUAL DO TRABALHO', ch: 70, status: 'a Cursar' },
          { code: '300020', name: 'MICROECONOMIA', ch: 70, status: 'a Cursar' },
          { code: '31', name: 'MATEMÁTICA FINANCEIRA', ch: 70, status: 'a Cursar' },
        ],
      },
      {
        etapa: 10,
        subjects: [
          { code: '238', name: 'GESTÃO DA QUALIDADE', ch: 70, status: 'a Cursar' },
          { code: '2558', name: 'MERCADO DE CAPITAIS', ch: 70, status: 'a Cursar' },
          { code: '2748', name: 'GOVERNANÇA CORPORATIVA', ch: 70, status: 'a Cursar' },
          { code: 'A13', name: 'AVALIAÇÃO INTEGRADA III - ADMINISTRAÇÃO', ch: 35, status: 'a Cursar' },
          { code: 'F00481', name: 'ACE - CULTURAL', ch: 100, status: 'a Cursar' },
        ],
      },
      {
        etapa: 11,
        subjects: [
          { code: '101', name: 'ADMINISTRAÇÃO DA PRODUÇÃO', ch: 70, status: 'a Cursar' },
          { code: '1033', name: 'LOGÍSTICA EMPRESARIAL', ch: 70, status: 'a Cursar' },
          { code: '2418', name: 'MÉTODOS QUANTITATIVOS ESTATÍSTICOS', ch: 70, status: 'a Cursar' },
        ],
      },
      {
        etapa: 12,
        subjects: [
          { code: '228', name: 'GESTÃO MERCADOLÓGICA', ch: 70, status: 'a Cursar' },
          { code: '2421', name: 'SISTEMAS DE INFORMAÇÕES GERENCIAIS', ch: 70, status: 'a Cursar' },
          { code: '892', name: 'PROJETO INTEGRADOR III', ch: 50, status: 'a Cursar' },
          { code: 'A14', name: 'AVALIAÇÃO INTEGRADA IV - ADMINISTRAÇÃO', ch: 35, status: 'a Cursar' },
        ],
      },
    ],
  },
];

export const certificates: Certificate[] = [
  {
    id: 'dio1',
    name: 'Acelerando Sua Produtividade Pessoal com IA',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 1,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio2',
    name: 'Aplicações Práticas da Inteligência Artificial',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 2,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio3',
    name: 'Boas vindas Ao Bootcamp HEINEKEN - Inteligência Artificial Aplicada a Vendas',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 1,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio4',
    name: 'Copiloto de Vendas com IA para Atendimento ao Cliente',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 4,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio5',
    name: 'Fundamentos da IA Moderna: Machine Learning, LLMs, IA Generativa e Agentes',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 2,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio6',
    name: 'Introdução à Engenharia de Prompts',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 1,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio7',
    name: 'Quem Não Vende, Ajuda a Vender! O Poder da Argumentação Comercial com IA',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 1,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio8',
    name: 'Simplificando Tarefas e Ganhando Foco com IA no Dia a Dia',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 1,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio9',
    name: 'Técnicas de Engenharia de Prompt',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 2,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio10',
    name: 'Transformando Sua Rotina com IA: Tenha o Seu Próprio Assistente de Metas',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 1,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio11',
    name: 'Treinando uma IA de Aprendizagem: Explore o Poder do NotebookLM',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 4,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'dio12',
    name: 'Tudo o que Você Precisa Saber para Começar a Usar Inteligência Artificial',
    institution: 'DIO.me',
    conclusionDate: '27/05/2026',
    durationHours: 2,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'c1',
    name: 'Preparando Dados para Análise - Microsoft Power BI',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '28/05/2026',
    durationHours: 7,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'c2',
    name: 'Trilha de Conhecimento Finanças',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '27/05/2026',
    durationHours: 40,
    year: 2026,
    category: 'Finanças',
  },
  {
    id: 'c3',
    name: 'Introdução à Análise de Dados - Microsoft Power BI',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '28/05/2026',
    durationHours: 5,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'c4',
    name: 'Contabilidade Empresarial',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '27/05/2026',
    durationHours: 10,
    year: 2026,
    category: 'Finanças',
  },
  {
    id: 'c5',
    name: 'Matemática Financeira com o uso da HP 12C',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '27/05/2026',
    durationHours: 20,
    year: 2026,
    category: 'Finanças',
  },
  {
    id: 'c6',
    name: 'Análise de Balanços',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '27/05/2026',
    durationHours: 10,
    year: 2026,
    category: 'Finanças',
  },
  {
    id: 'c7',
    name: 'Introdução à Administração',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '17/01/2019',
    durationHours: 12,
    year: 2019,
    category: 'Administração',
  },
  {
    id: 'c8',
    name: 'Atendimento ao Público',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '17/01/2019',
    durationHours: 10,
    year: 2019,
    category: 'Comunicação/Pessoal',
  },
  {
    id: 'c9',
    name: 'Postura e Imagem Profissional (PIP)',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '16/04/2019',
    durationHours: 10,
    year: 2019,
    category: 'Comunicação/Pessoal',
  },
  {
    id: 'c10',
    name: 'Fundamentos de TI - Hardware e Software',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '16/04/2019',
    durationHours: 15,
    year: 2019,
    category: 'Tecnologia',
  },
  {
    id: 'c11',
    name: 'Comunicação Empresarial',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '16/04/2019',
    durationHours: 12,
    year: 2019,
    category: 'Comunicação/Pessoal',
  },
  {
    id: 'c12',
    name: 'Desenvolvimento Profissional',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '23/04/2019',
    durationHours: 10,
    year: 2019,
    category: 'Comunicação/Pessoal',
  },
  {
    id: 'c13',
    name: 'Microsoft Word 2013 - Intermediário',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '23/04/2019',
    durationHours: 13,
    year: 2019,
    category: 'Tecnologia',
  },
  {
    id: 'c14',
    name: 'Análise de Dados no Power BI',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '06/05/2026',
    durationHours: 4,
    year: 2026,
    category: 'Tecnologia',
  },
  {
    id: 'c15',
    name: 'Microsoft Excel 2016 - Avançado',
    institution: 'Fundação Bradesco - Escola Virtual',
    conclusionDate: '06/05/2026',
    durationHours: 30,
    year: 2026,
    category: 'Tecnologia',
  },
];

export const skills: SkillItem[] = [
  { name: 'Excel & Pacote Office', level: 'Avançado', progress: 95 },
  { name: 'Gestão Financeira & Administração', level: 'Avançado', progress: 90 },
  { name: 'Análise de Investimentos', level: 'Avançado', progress: 85 },
  { name: 'Contabilidade & Análise de Balanços', level: 'Avançado', progress: 85 },
  { name: 'Microsoft Power BI (Análise de Dados)', level: 'Intermediário', progress: 75 },
  { name: 'SAP ERP', level: 'Intermediário', progress: 65 },
  { name: 'Planejamento Estratégico', level: 'Avançado', progress: 85 },
  { name: 'Rotinas Administrativas & Contas a Pagar', level: 'Avançado', progress: 90 },
  { name: 'Gestão de Custos & Orçamentária', level: 'Avançado', progress: 80 },
  { name: 'Comunicação Verbal e Escrita', level: 'Avançado', progress: 95 },
];
